version: '7'

services:
  tts:
    image: zhouzhiyang/mm-voice-styletts2-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      LOG_LEVEL: WARNING
